###
@baseUrl = https://app-api-ocwiawb26beca.azurewebsites.net
@listName = My Todo List
@listDescription = A list of things to do
@currentDateTime = {{$datetime iso8601}}

###
# Create a Todo List
POST {{baseUrl}}/lists HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "name": "{{listName}}",
  "description": "{{listDescription}}"
}

@listId = {{response.parsedBody.id}}

###
# Create Item 1
POST {{baseUrl}}/lists/{{listId}}/items HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "listId": "{{listId}}",
  "name": "Buy groceries",
  "description": "Milk, bread, eggs",
  "state": "todo",
  "dueDate": "{{currentDateTime}}"
}

@item1Id = {{response.parsedBody.id}}

###
# Create Item 2
POST {{baseUrl}}/lists/{{listId}}/items HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "listId": "{{listId}}",
  "name": "Wash car",
  "description": "Outside and inside",
  "state": "todo",
  "dueDate": "{{currentDateTime}}"
}

@item2Id = {{response.parsedBody.id}}

###
# Get list details
GET {{baseUrl}}/lists/{{listId}} HTTP/1.1
Accept: application/json

###
# Get all items in the list
GET {{baseUrl}}/lists/{{listId}}/items HTTP/1.1
Accept: application/json

###
# Update Item 1
PUT {{baseUrl}}/lists/{{listId}}/items/{{item1Id}} HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "listId": "{{listId}}",
  "name": "Buy groceries (updated)",
  "description": "Milk, bread, eggs, and juice",
  "state": "inprogress",
  "dueDate": "{{currentDateTime}}",
  "completedDate": null
}

###
# Delete Item 2
DELETE {{baseUrl}}/lists/{{listId}}/items/{{item2Id}} HTTP/1.1
Accept: application/json

###
# Confirm remaining items after deletion
GET {{baseUrl}}/lists/{{listId}}/items HTTP/1.1
Accept: application/json

###
# Delete the Todo List
DELETE {{baseUrl}}/lists/{{listId}} HTTP/1.1
Accept: application/json
